#!/usr/bin/env sh

get_option() {
	local res=$(tmux show-option -gqv "$1")
	echo "${res:-$2}"
}

tome_height=$(get_option "@tome_height" 8)
tome_playbook=$(get_option "@tome_playbook" .playbook.sh)

if [ "$1" = "-s" ]; then
	# open scratchpad
	tmux split-window -c '#{pane_current_path}' -vb -l $tome_height "vim -c TomeScratchPad"
else
	# open tome playbook
	tmux split-window -c '#{pane_current_path}' -vb -l $tome_height "vim -c TomePlayBook $tome_playbook"
fi
