#!/bin/sh

get_option() {
	res=$(tmux show-option -gqv "$1")
	echo "${res:-$2}"
}

tome_height=$(get_option "@tome_height" 8)
tome_playbook=$(get_option "@tome_playbook" .playbook.sh)
tome_editor=$(get_option "@tome_editor" -)
scratchpad=0

while getopts 'sl:h' opt; do
	case "$opt" in
	s) scratchpad=1 ;;
	l) tome_height=$OPTARG ;;
	*)
		echo "Usage: $(basename "$0") [-s] [-l height]"
		exit 1
		;;
	esac
done

if [ $tome_editor = '-' ]; then
	# detect (n)vim
	case "$EDITOR" in
	*nvim*)
		tome_editor="nvim"
		;;
	*)
		tome_editor="vim"
		;;
	esac
fi

if [ $scratchpad = 1 ]; then
	# open scratchpad
	tmux split-window -c '#{pane_current_path}' -vb -l "$tome_height" "$tome_editor -c TomeScratchPad"
else
	# open tome playbook
	tmux split-window -c '#{pane_current_path}' -vb -l "$tome_height" "$tome_editor -c TomePlayBook $tome_playbook"
fi
