#!/bin/bash
set -eE -o pipefail

script_dir=$(dirname "$(realpath "$0")")
cd $script_dir/..

if ! shfmt -p -d tome-open-playbook tome.tmux; then
  echo
  echo "please apply scripts/fixfmt before you commit"
  exit 1
fi
