#!/bin/bash
set -eE -o pipefail

script_dir=$(dirname "$(realpath "$0")")
cd $script_dir/..

if ! shfmt -p -i 4 -bn -ci -sr -d tome-open-playbook tome.tmux scripts/*; then
    echo
    echo "please apply scripts/fixfmt before you commit"
    exit 1
else
    echo "all OK!"
fi
